steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/sportvia/sportvia:$SHORT_SHA", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/sportvia/sportvia:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "sportvia",
        "--image=gcr.io/sportvia/sportvia:$SHORT_SHA",
        "--platform=managed",
        "--region=us-east1",
      ]
